const comparisonContent: Record<string, string> = {
  en: String.raw`# zoxide vs autojump: a practical comparison

zoxide and autojump solve the same everyday problem: returning to a directory you have visited before without typing its full path. Both maintain a local directory database and learn from normal shell use. The important differences are not a single unverified speed number, but how each tool integrates with shells, handles ambiguous matches, supports current platforms, and fits an existing workflow.

This comparison uses the behavior documented by the two upstream projects. It does not claim a universal benchmark: shell startup time and query latency vary with the operating system, shell framework, database size, storage, and configuration. For most people, the larger productivity gain comes from fewer keystrokes and fewer navigation mistakes.

## Quick answer

Choose **zoxide** when you want current support across macOS, Linux, and Windows, direct multi-term matching, optional interactive selection through fzf, and an official import path from autojump. Keep **autojump** when its j, jc, jo, and jco commands already fit a stable setup and you do not need zoxide's shell or platform coverage.

There is no need to uninstall autojump before testing zoxide. Their default commands are different—j for autojump and z for zoxide—so you can run both for a short evaluation, compare results using your real directory history, and remove the old integration only after the new one is reliable.

If you are starting on Linux, complete the [Ubuntu 24.04 installation guide](/tutorials/install-ubuntu) or the matching platform setup before comparing commands. When z works, the [fzf integration guide](/tutorials/fzf-integration) shows how to test zi with a compatible selector.

## Feature comparison

| Area | zoxide | autojump |
| --- | --- | --- |
| Default jump command | z | j |
| Learning model | Ranks visited directories with a frecency-style algorithm | Maintains weights for frequently used directories |
| Multiple query terms | z client portal | j client portal |
| Interactive selection | zi, using separately installed fzf | No equivalent interactive picker documented in the main upstream README |
| File-manager shortcut | Compose a query with an OS-specific open command | jo and jco are documented shortcuts |
| Primary implementation | Rust | Python |
| Upstream platform statement | macOS, Linux, and Windows | Linux and macOS first-class; Windows and BSD community-supported |
| Shell setup | Generated by zoxide init for major shells | Installation supplies shell integration; support level varies by shell |
| Import existing history | zoxide import autojump | Not applicable when staying on autojump |

The table is a starting point, not a substitute for testing. In particular, package versions supplied by an operating system can lag behind upstream releases, and shell plugin managers can change startup behavior for either tool.

## Matching and daily commands

Both tools require a directory to be visited before it becomes a useful learned target. If ~/work/client-portal has never been seen, neither tool should be treated as a full filesystem search engine.

With zoxide:

~~~bash
z portal          # jump to the best learned match
z client portal   # add another path fragment
zi portal         # choose interactively with fzf
zoxide query portal
~~~

With autojump:

~~~bash
j portal          # jump to a learned match
j client portal   # use multiple arguments
jc portal         # prefer a child directory
jo music          # open a learned directory in a file manager
~~~

zoxide's zi command is helpful on machines that contain many similar repositories because it makes ambiguity visible before changing directory. It requires fzf, which is optional and installed separately. autojump's jo and jco commands are useful if opening a learned path in Finder, Explorer, or another file manager is part of the normal workflow.

## Shell and platform fit

The zoxide project documents setup for Bash, Zsh, Fish, PowerShell, Nushell, Elvish, Tcsh, Xonsh, and POSIX shells. Its Windows instructions cover PowerShell as well as Cygwin, Git Bash, and MSYS2, with winget listed as the recommended Windows installation route.

autojump documents Bash and Zsh as first-class shells. Fish, Tcsh, and Clink are community-supported. Its project documentation describes Linux and macOS as first-class platforms, while Windows support depends on Clink and is community-supported. That distinction does not make autojump unusable on Windows; it means a Windows-first user should verify the exact shell and package path before committing to it.

If you work on several operating systems and want similar commands everywhere, zoxide generally provides the simpler documented path. If you have one long-lived Bash or Zsh setup where autojump already behaves correctly, migration is optional rather than urgent.

## Performance without invented numbers

zoxide is implemented in Rust and autojump in Python, but implementation language alone is not a benchmark. A fair measurement must include the generated shell hook, shell framework, plugin load order, database size, warm and cold starts, and the exact operation being timed. Numbers copied from an unrelated machine can be misleading.

Measure the behavior you actually notice. Time a clean interactive shell with and without each initialization line, then repeat representative queries against the same learned directories. More importantly, record wrong selections and how often a query needs correction. Saving a few milliseconds is not useful if a broad keyword repeatedly opens the wrong project.

For most workflows, the practical comparison is:

- How many characters are needed to reach a frequent directory?
- Can ambiguous matches be inspected before jumping?
- Does the hook behave correctly with the existing prompt and plugin manager?
- Is configuration consistent across every machine you use?
- Can the database be inspected and cleaned without guesswork?

## A low-risk migration from autojump

1. Install zoxide with the package method recommended for your operating system.
2. Add the matching zoxide init line to the shell profile, but keep the autojump setup temporarily.
3. Open a new shell and confirm that zoxide --version and z --help both work.
4. Import the existing directory history:

~~~bash
zoxide import autojump
~~~

5. Compare familiar destinations with j and z. Use zoxide query --list to inspect imported entries and remove stale paths individually.
6. Work with both tools for several sessions. Check ambiguous project names, paths containing spaces, and every shell you use.
7. When zoxide is reliable, remove the autojump initialization from the shell profile and uninstall autojump with the package manager that installed it.

Do not delete the autojump database at the beginning. Keeping it until the import and real-world checks succeed gives you a straightforward rollback.

## Which one should you choose?

**Start with zoxide** if this is a new setup, if Windows or PowerShell is important, if you want an fzf-backed interactive chooser, or if you move between several shells. Its official import command also makes it the easier tool to trial when you already have autojump history.

**Keep autojump** if the existing j-family commands are part of your muscle memory, jo/jco file-manager actions are valuable, and the current shell integration has been stable. A working navigation tool does not become bad merely because another project offers more integrations.

Whichever tool you choose, keep cd for exact paths and scripts. Learned ranking is designed for interactive convenience; automation should use deterministic locations.

## Sources and verification

The commands and support statements above were checked on August 6, 2026 against the [zoxide upstream repository](https://github.com/ajeetdsouza/zoxide), its [matching algorithm notes](https://github.com/ajeetdsouza/zoxide/wiki/Algorithm), and the [autojump upstream repository](https://github.com/wting/autojump). If the new command does not load after migration, use the [command-not-found diagnostic](/blog/zoxide-command-not-found). Check the current release documentation before rolling a configuration out to multiple machines.`,

  zh: String.raw`# zoxide 与 autojump 的真实工作流比较

zoxide 和 autojump 解决同一个高频问题。目录访问过一次后，以后不再输入完整路径。两者都会在本机维护目录数据库，并从日常 Shell 使用中积累权重。值得比较的项目包括 Shell 集成、歧义处理、平台支持和迁移成本。没有测试环境的“快 10 倍”数字无法回答这些问题。

本文只采用两个上游项目公开文档可以核验的行为，不给出所谓通用毫秒基准。Shell 启动与查询耗时会受到操作系统、Shell 框架、数据库大小、磁盘和配置影响。对大多数人而言，主要收益来自少敲字符、少记路径，以及更少跳错目录。

## 先给结论

如果你希望在 macOS、Linux、Windows 上使用相近的配置，需要多关键词匹配、fzf 交互选择，或准备从 autojump 导入历史，优先试用 **zoxide**。如果现有的 j、jc、jo、jco 已经稳定融入工作流，而且不需要更广的 Shell/平台覆盖，继续使用 **autojump** 也完全合理。

试用 zoxide 前不必卸载 autojump。两者默认命令不同。autojump 使用 j，zoxide 使用 z。可以并行运行一段时间，用自己的真实目录库比较结果，确认新工具可靠后再移除旧集成。

如果从 Linux 新环境开始，可以先完成 [Ubuntu 24.04 安装教程](/tutorials/install-ubuntu) 或对应平台的配置。确认 z 正常后，再按 [fzf 配置教程](/tutorials/fzf-integration) 检查 zi 和选择器版本。

## 功能对照

| 维度 | zoxide | autojump |
| --- | --- | --- |
| 默认跳转命令 | z | j |
| 学习方式 | 使用类似 frecency 的算法为访问目录排序 | 为常用目录维护权重 |
| 多关键词 | z client portal | j client portal |
| 交互选择 | zi，依赖单独安装的 fzf | 上游主 README 未提供同类交互选择器 |
| 打开文件管理器 | 可把查询结果与系统 open 命令组合 | 官方文档提供 jo 和 jco |
| 主要实现语言 | Rust | Python |
| 上游平台表述 | macOS、Linux、Windows | Linux/macOS 为一等支持；Windows/BSD 为社区支持 |
| Shell 配置 | zoxide init 为主流 Shell 生成初始化脚本 | 安装后加载相应 Shell 集成，支持级别因 Shell 而异 |
| 导入旧历史 | zoxide import autojump | 留在 autojump 时不需要迁移 |

这张表只适合做第一轮筛选。操作系统软件源里的版本可能落后于上游，Shell 插件管理器也可能改变两者的启动行为，最终仍应在自己的环境验证。

## 匹配方式和日常命令

两个工具都要先“见过”目录，才能把它作为可靠候选。如果 ~/work/client-portal 从未访问过，它们都不应该被当成扫描整块磁盘的搜索工具。

zoxide 的常见命令如下。

~~~bash
z portal          # 跳到排名最高的已学习目录
z client portal   # 用另一个路径片段缩小范围
zi portal         # 通过 fzf 交互选择
zoxide query portal
~~~

autojump 的常见命令如下。

~~~bash
j portal          # 跳到一个已学习目标
j client portal   # 使用多个关键词
jc portal         # 优先选择当前目录下的子目录
jo music          # 在文件管理器中打开已学习目录
~~~

两种工具照顾的工作流不同。机器上有大量同名仓库时，zoxide 的 zi 可以在跳转前展示歧义，不过它依赖单独安装的 fzf。经常需要在 Finder、Explorer 或其他文件管理器中打开目标的人，则能直接用 autojump 的 jo/jco。

## Shell 与平台适配

zoxide 上游列出了 Bash、Zsh、Fish、PowerShell、Nushell、Elvish、Tcsh、Xonsh 和 POSIX Shell 的配置。Windows 说明覆盖 PowerShell、Cygwin、Git Bash 和 MSYS2，并把 winget 列为 Windows 推荐安装方式。

autojump 把 Bash、Zsh 列为一等支持，Fish、Tcsh、Clink 为社区支持；平台方面，Linux 和 macOS 是一等支持，Windows 通过 Clink 实现并归为社区支持。autojump 在 Windows 仍可使用，采用前需要更仔细地核对具体 Shell 和安装路径。

如果你在多台不同系统之间工作，希望命令和配置尽量一致，zoxide 的文档路径通常更直接。只维护一套长期稳定的 Bash/Zsh 环境，并且 autojump 已经正常工作时，迁移只是一项可选调整。

## 不用虚构数字比较性能

zoxide 主要用 Rust 编写，autojump 用 Python 编写，但实现语言本身不构成完整基准。公平测试必须交代生成的 Shell 钩子、Shell 框架、插件顺序、数据库规模、冷热启动和具体操作。把另一台机器的数字直接搬过来，很容易误导读者。

应该测量自己能感知的环节。分别启用两种初始化并比较新 Shell 启动，再用相同的目录历史测试常见查询。还要记录错误匹配率，以及一个查询需要补充多少次关键词。如果宽泛关键词总把你带到错误项目，少几毫秒没有实际帮助。

实际评估可以回答下面五个问题。

- 到达常用目录要输入多少字符？
- 多个候选时能否在跳转前确认？
- 钩子是否与现有提示符和插件管理器兼容？
- 你使用的每台机器能否保持相近配置？
- 数据库能否方便地查看和定向清理？

## 从 autojump 低风险迁移

1. 按操作系统选择上游推荐方式安装 zoxide。
2. 在 Shell 配置中加入对应的 zoxide init 行，暂时保留 autojump。
3. 新开终端，确认 zoxide --version 和 z --help 都正常。
4. 导入现有目录历史。

~~~bash
zoxide import autojump
~~~

5. 对熟悉的目标分别运行 j 和 z。用 zoxide query --list 检查导入记录，只删除确实过期的路径。
6. 并行使用几个会话，重点测试同名项目、带空格路径和你实际使用的每一种 Shell。
7. 确认 zoxide 稳定后，从配置文件删除 autojump 初始化，再用原包管理器卸载 autojump。

一开始不要删除 autojump 数据库。等导入和真实使用都通过后再清理，才有简单明确的回退路径。

## 到底应该选哪个？

新装环境、重视 Windows/PowerShell、需要 fzf 交互选择，或经常跨多个 Shell 时，建议先试 **zoxide**。已有 autojump 历史的人也能通过官方 import 命令快速验证，不必从零积累。

如果 j 系列命令已经形成肌肉记忆，jo/jco 的文件管理器操作很重要，并且当前 Shell 集成多年稳定，可以继续用 **autojump**。一个可靠工具不会因为另一个项目集成更多就突然失去价值。

无论选择哪个，都建议保留 cd 用于准确路径和脚本。动态学习排名适合交互便利，自动化应使用确定性位置。

## 资料来源

本文命令与支持范围于 2026 年 8 月 6 日对照 [zoxide 上游仓库](https://github.com/ajeetdsouza/zoxide)、[匹配算法说明](https://github.com/ajeetdsouza/zoxide/wiki/Algorithm) 和 [autojump 上游仓库](https://github.com/wting/autojump) 核验。迁移后若命令没有加载，可按 [command not found 排查教程](/blog/zoxide-command-not-found) 检查。批量配置多台机器前，请再次查看当前版本文档。`,

  ja: String.raw`# zoxide と autojump：実際のワークフローで比較する

zoxide と autojump は、以前訪れたディレクトリへ完全なパスを入力せず戻る、という同じ問題を解決します。どちらもローカルにディレクトリデータを持ち、通常のシェル利用から重みを学習します。比較すべきなのは根拠のない「10倍」という数字ではなく、シェル統合、曖昧な候補の扱い、対応プラットフォーム、移行コストです。

このページは、両上流プロジェクトの公開文書で確認できる動作を基準にします。普遍的なミリ秒値は示しません。起動やクエリ時間は OS、シェルフレームワーク、データベース量、ストレージ、設定で変わります。多くの人にとって大きな効果は、入力文字と経路の記憶、誤移動を減らすことです。

## 先に結論

macOS、Linux、Windows で似た構成を使いたい、複数語検索や fzf による対話選択が欲しい、autojump の履歴を移したい場合は **zoxide** を先に試す価値があります。j、jc、jo、jco が安定した既存環境に合い、より広いシェル対応を必要としないなら **autojump** を継続しても問題ありません。

試用前に autojump を削除する必要はありません。既定コマンドは autojump が j、zoxide が z なので、一時的に併用できます。実際の履歴で結果を比べ、新しい設定を確認してから古い統合を外します。

Linux の新規環境なら、先に [Ubuntu 24.04 インストールガイド](/tutorials/install-ubuntu) または利用 OS の設定を完了します。z が動いた後、[fzf 連携ガイド](/tutorials/fzf-integration) で zi と選択ツールの版を確認できます。

## 機能比較

| 項目 | zoxide | autojump |
| --- | --- | --- |
| 既定ジャンプ | z | j |
| 学習 | frecency 型で訪問ディレクトリを順位付け | よく使うディレクトリの重みを維持 |
| 複数語 | z client portal | j client portal |
| 対話選択 | 別途 fzf を使う zi | 上流メイン README には同等の選択 UI の記載なし |
| ファイル管理画面 | OS の open コマンドとクエリを組み合わせる | jo と jco を公式文書で案内 |
| 主な実装 | Rust | Python |
| 上流の対応表現 | macOS、Linux、Windows | Linux/macOS は first-class、Windows/BSD は community-supported |
| シェル設定 | zoxide init が主要シェル向けコードを生成 | インストール後に各シェル統合を読み込む |
| 既存履歴 | zoxide import autojump | autojump を継続するなら移行不要 |

OS のパッケージが上流より古い場合や、シェルのプラグイン管理が起動順を変える場合があります。この表は候補を絞る材料であり、自分の環境での確認を置き換えるものではありません。

## マッチングと日常コマンド

どちらも、ディレクトリを一度訪れてから有用な候補になります。~/work/client-portal を見たことがなければ、ファイルシステム全体を検索する道具として扱うべきではありません。

zoxide：

~~~bash
z portal          # 学習済み候補の最上位へ移動
z client portal   # パス断片を追加
zi portal         # fzf で対話選択
zoxide query portal
~~~

autojump：

~~~bash
j portal          # 学習した候補へ移動
j client portal   # 複数引数で候補を絞る
jc portal         # 子ディレクトリを優先
jo music          # ファイルマネージャーで開く
~~~

同名リポジトリが多い端末では、zoxide の zi が移動前に曖昧さを見せてくれます。ただし fzf は別途必要です。Finder や Explorer で学習済みパスを開くことが多いなら、autojump の jo/jco は明確な利点です。

## シェルとプラットフォーム

zoxide は Bash、Zsh、Fish、PowerShell、Nushell、Elvish、Tcsh、Xonsh、POSIX シェルの設定を案内しています。Windows では PowerShell に加え Cygwin、Git Bash、MSYS2 を説明し、winget を推奨インストール方法としています。

autojump は Bash と Zsh を first-class、Fish、Tcsh、Clink を community-supported と説明します。プラットフォームは Linux と macOS が first-class、Windows は Clink を使う community-supported です。Windows で使えないという意味ではなく、採用前に利用シェルと導入経路を確認する必要があります。

複数 OS でコマンドを揃えたい場合、zoxide の文書経路は比較的単純です。一つの Bash/Zsh 環境で autojump が長く安定しているなら、移行は必須ではありません。

## 根拠のない性能値を使わない

zoxide は Rust、autojump は Python が中心ですが、言語だけで性能は決まりません。公平な測定には、シェルフック、フレームワーク、プラグイン順、DB サイズ、コールド/ウォーム起動、対象操作を含める必要があります。別の端末の数字をそのまま掲載すると誤解を招きます。

実際に気になる動作を測ります。各 init 行を有効・無効にして新規シェルを比較し、同じ履歴で代表的なクエリを繰り返します。さらに、誤った候補の回数と追加語の必要回数も記録します。数ミリ秒短くても、毎回違うプロジェクトへ飛ぶなら実用上速くありません。

確認すべき点は次の五つです。

- 常用ディレクトリまで何文字必要か
- 候補が複数あるとき移動前に確認できるか
- 現在のプロンプトやプラグインと競合しないか
- 使う全端末で似た設定にできるか
- データベースを一覧・個別削除できるか

## autojump から安全に移行する

1. OS 向けの上流推奨方法で zoxide をインストール。
2. 対応する zoxide init を設定し、autojump は一時的に残す。
3. 新しいシェルで zoxide --version と z --help を確認。
4. 履歴をインポート：

~~~bash
zoxide import autojump
~~~

5. よく使う目的地を j と z で比較。zoxide query --list で取り込み内容を確認し、古いパスだけを削除。
6. 複数セッションで、同名プロジェクト、空白入りパス、利用中の各シェルを試す。
7. 安定したら autojump の初期化を外し、導入時のパッケージマネージャーで削除。

最初に autojump のデータベースを消さないでください。インポートと実利用の確認後まで残せば、戻す手順が簡単です。

## どちらを選ぶか

新規環境、Windows/PowerShell 重視、fzf 選択、複数シェル利用なら、まず **zoxide** が候補です。autojump の履歴も公式 import で検証できるため、ゼロから学習し直す必要はありません。

j 系コマンドが身についており、jo/jco が重要で、現在の統合が安定しているなら **autojump** を維持できます。連携数が多い別ツールが存在しても、動いている道具の価値は失われません。

どちらの場合も、正確なパスとスクリプトには cd を残します。学習順位は対話操作の便利さのためのもので、自動化は決定的な場所を使うべきです。

## 出典

コマンドと対応範囲は 2026 年 8 月 6 日に [zoxide 上流リポジトリ](https://github.com/ajeetdsouza/zoxide)、[マッチングアルゴリズムの説明](https://github.com/ajeetdsouza/zoxide/wiki/Algorithm)、[autojump 上流リポジトリ](https://github.com/wting/autojump) で確認しました。移行後にコマンドが読み込まれない場合は [command not found の診断](/blog/zoxide-command-not-found) を参照してください。複数端末へ展開する前に、現在のリリース文書を再確認してください。`,
};

export function getBlogContentOverride(locale: string, slug: string): string | undefined {
  if (slug !== "zoxide-vs-autojump") {
    return undefined;
  }

  return comparisonContent[locale] || comparisonContent.en;
}
